tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "openssl@1.1"
brew "readline"
brew "docker"
brew "docker-machine"
brew "pkg-config"
brew "libtool"
brew "nginx", restart_service: true
brew "nvm"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "wget"
